### ISSUE TITLE
swarm logical operators

### ISSUE THREAD

**Issue by aheinz-fe** [vivisect/synapse#23]
In order to be able to generate arbitrary queries, end users need to be able to use common logical operators (NOT, OR and AND) in the swarm query language. Some operations can be achieved via rewrites, but not all.

propositional | possible
--- | ---
cant(¬ foo) | must(foo)
cant(foo ∧ bar) | **NEEDED**
cant(foo ∨ bar) | cant(foo) cant(bar)
must(¬ foo) | cant(foo)
must(foo ∧ bar) | must(foo) must(bar)
must(foo ∨ bar) | **NEEDED**

Please include support for the short hand notation.

**Comment by invisig0th** [comment]
Love the formal logic table :)

So, in iris each filtration operator actually implemented a filter function that was expected to be reversible and was aware of + and - prefixes.  It ended up requiring a subclass for each operator ( rather than just one function ) but was pretty nice because you could implement a single evaluator and get the intuitive:

+foo()
-foo()

This would basically fold the lift(), must(), cant() operators into one, and allow things like:
+tags(foo)
-tags(foo)

which seems more intuitive.

I'd be happy to implement that here, and would expect it to cause little-to-no issues if you cats are exclusively using macro syntax ( i think i've been leaning toward going this way ever since having to make separate operators for inclusive vs exclusive filtration based on the same logic )

Thoughts?

**Comment by aheinz-fe** [comment]
How are filter functions registered with the swarm query runtime? If I am able to register things just in time, I could write a preprocessor that converts fully grouped expressions like (foo ∨ (bar ∧ ¬ baz)) to a filter function, executes it, then throws it away.

**Comment by invisig0th** [comment]
Actually, if we were to limit the syntax parsing to logical operators operating (with precedence) operating on existence, equality, and less/greater, we could probably implement a simple parser for arbitrary nested logic (not nested operators) simply enough....


foo & (bar>=30 | !baz=10)

If we were to cut the guts over to the iris way, the filter functions in the language would be subclasses of the basic operator and implement one method ( which is used in both the must and the cant case )

**Comment by aheinz-fe** [comment]
Implemented by https://github.com/vivisect/synapse/commit/9c6b081d13adf95b8cc84ec798209f2568c36903
